# Nome do Workflow
name: DevOpsLab Pipeline

# Evento que irá acionar a pipeline
on: 
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.11'

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install Requirements - Flask
        run:  pip install flask

      - name: Install Requirements - Flask WTF
        run:  pip install flask flask-wtf

      - name: Install Requirements - Flask Cors
        run:  pip install flask-cors

      - name: Install Requirements - PyMySQL
        run:  pip install PyMySQL

      - name: Install Requirements - cryptography
        run:  pip install cryptography

      - name: Install Requirements - gunicorn
        run:  pip install gunicorn

      - name: Install Requirements - Tox
        run:  pip install tox